import { Budget } from "@/types/Budget";
import { User } from "@/types/User";
import { Category } from "@/types/CategoryEnum";

export const budget: Budget = {
    id: 1,
    month: "March",
    description: "Budget for the month of October 2030",
    createdAt: new Date(),
    updatedAt: new Date(),
    year: '2025',
    userId: '',
    income: [
        {id: 1,
        source: 'salary',
        amount: 2500,
        description: 'monthly salary'
        },
        {id: 2,
        source: 'Gift',
        amount: 50,
        description: 'Birthday gift from a friend',
        },
        {id: 3,
            source: 'Bonus',
            amount: 150,
            description: 'Bonus for vacation',
        },
        {id: 4,
            source: 'returns',
            amount: 100,
            description: 'Returns from investment',
        }
    ],
    expenses: [
        {
            id: 1,
            title: "Rice",
            amount: 20,
            category: Category.GROCERIES,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            id: 2,
            title: "Tioletries",
            amount: 12,
            category: Category.GROCERIES,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
       
        {
            id: 3,
            title: "Vegetable oil",
            amount: 8,
            category: Category.GROCERIES,
            createdAt: new Date(),
            updatedAt: new Date(),
        }, 
        {
            id: 4,
            title: "Chicken",
            amount: 10,
            category: Category.GROCERIES,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            id: 5,
            title: "Eggs",
            amount: 9,
            category: Category.GROCERIES,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            id: 6,
            title: "Kinder milk",
            amount: 200,
            category: Category.GROCERIES,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            id: 7,
            title: "fess",
            amount: 170,
            category: Category.KIDS,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            id: 8,
            title: "House rent",
            amount: 1200,
            category: Category.BILLS,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            id: 9,
            title: "Electricity",
            amount: 70,
            category: Category.BILLS,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            id: 10,
            title: "Internet",
            amount: 20,
            category: Category.BILLS,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            id: 11,
            title: "transport",
            amount: 49,
            category: Category.BILLS,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            id: 12,
            title: "savings",
            amount: 500,
            category: Category.SAVINGS,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            id: 13,
            title: "Miscellaneous",
            amount: 200,
            category: Category.BILLS,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
    ]
}

export const user: User = {
    id: 1,
    name: 'Funmilola Fawole',
    email: 'funmilolafawole@gmail.com',
    password: 'funmi4real'
}

export const budgets: Array<Budget> = [
    {
        id: 1,
        month: "March",
        description: "Budget for the month of October 2030",
        createdAt: new Date(),
        updatedAt: new Date(),
        year: '2025',
        userId: '',
        income: [
            {id: 1,
            source: 'salary',
            amount: 2500,
            description: 'monthly salary'
            },
            {id: 2,
            source: 'Gift',
            amount: 100,
            description: 'Birthday gift from a friend',
            },
            {id: 3,
                source: 'Bonus',
                amount: 150,
                description: 'Bonus for vacation',
            },
            {id: 4,
                source: 'returns',
                amount: 100,
                description: 'Returns from investment',
            }
        ],
        expenses: [
            {
                id: 1,
                title: "Rice",
                amount: 20,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 2,
                title: "Tioletries",
                amount: 12,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
           
            {
                id: 3,
                title: "Vegetable oil",
                amount: 8,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            }, 
            {
                id: 4,
                title: "Chicken",
                amount: 10,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 5,
                title: "Eggs",
                amount: 9,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 6,
                title: "Kinder milk",
                amount: 200,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 7,
                title: "fess",
                amount: 170,
                category: Category.KIDS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 8,
                title: "House rent",
                amount: 1200,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 9,
                title: "Electricity",
                amount: 70,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 10,
                title: "Internet",
                amount: 20,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 11,
                title: "transport",
                amount: 49,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 12,
                title: "savings",
                amount: 500,
                category: Category.SAVINGS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 13,
                title: "Miscellaneous",
                amount: 200,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
        ]
    },
    {
        id: 2,
        month: "April",
        description: "Budget for the month of October 2030",
        createdAt: new Date(),
        updatedAt: new Date(),
        year: '2025',
        userId: '',
        income: [
            {id: 1,
            source: 'salary',
            amount: 2500,
            description: 'monthly salary'
            },
            {id: 2,
            source: 'Gift',
            amount: 100,
            description: 'Birthday gift from a friend',
            },
            {id: 3,
                source: 'Bonus',
                amount: 150,
                description: 'Bonus for vacation',
            },
            {id: 4,
                source: 'returns',
                amount: 100,
                description: 'Returns from investment',
            }
        ],
        expenses: [
            {
                id: 1,
                title: "Rice",
                amount: 20,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 2,
                title: "Tioletries",
                amount: 12,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
           
            {
                id: 3,
                title: "Vegetable oil",
                amount: 8,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            }, 
            {
                id: 4,
                title: "Chicken",
                amount: 10,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 5,
                title: "Eggs",
                amount: 9,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 6,
                title: "Kinder milk",
                amount: 200,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 7,
                title: "fess",
                amount: 170,
                category: Category.KIDS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 8,
                title: "House rent",
                amount: 1200,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 9,
                title: "Electricity",
                amount: 70,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 10,
                title: "Internet",
                amount: 20,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 11,
                title: "transport",
                amount: 49,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 12,
                title: "savings",
                amount: 500,
                category: Category.SAVINGS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 13,
                title: "Miscellaneous",
                amount: 200,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
        ]
    },
    {
        id: 3,
        month: "May",
        description: "Budget for the month of October 2030",
        createdAt: new Date(),
        updatedAt: new Date(),
        year: '2025',
        userId: '',
        income: [
            {id: 1,
            source: 'salary',
            amount: 2500,
            description: 'monthly salary'
            },
            {id: 2,
            source: 'Gift',
            amount: 100,
            description: 'Birthday gift from a friend',
            },
            {id: 3,
                source: 'Bonus',
                amount: 150,
                description: 'Bonus for vacation',
            },
            {id: 4,
                source: 'returns',
                amount: 100,
                description: 'Returns from investment',
            }
        ],
        expenses: [
            {
                id: 1,
                title: "Rice",
                amount: 20,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 2,
                title: "Tioletries",
                amount: 12,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
           
            {
                id: 3,
                title: "Vegetable oil",
                amount: 8,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            }, 
            {
                id: 4,
                title: "Chicken",
                amount: 10,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 5,
                title: "Eggs",
                amount: 9,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 6,
                title: "Kinder milk",
                amount: 200,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 7,
                title: "fess",
                amount: 170,
                category: Category.KIDS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 8,
                title: "House rent",
                amount: 1200,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 9,
                title: "Electricity",
                amount: 70,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 10,
                title: "Internet",
                amount: 20,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 11,
                title: "transport",
                amount: 49,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 12,
                title: "savings",
                amount: 500,
                category: Category.SAVINGS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 13,
                title: "Miscellaneous",
                amount: 200,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
        ]
    },
    {
        id: 4,
        month: "June",
        description: "Budget for the month of October 2030",
        createdAt: new Date(),
        updatedAt: new Date(),
        year: '2025',
        userId: '',
        income: [
            {id: 1,
            source: 'salary',
            amount: 2500,
            description: 'monthly salary'
            },
            {id: 2,
            source: 'Gift',
            amount: 100,
            description: 'Birthday gift from a friend',
            },
            {id: 3,
                source: 'Bonus',
                amount: 150,
                description: 'Bonus for vacation',
            },
            {id: 4,
                source: 'returns',
                amount: 100,
                description: 'Returns from investment',
            }
        ],
        expenses: [
            {
                id: 1,
                title: "Rice",
                amount: 20,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 2,
                title: "Tioletries",
                amount: 12,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
           
            {
                id: 3,
                title: "Vegetable oil",
                amount: 8,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            }, 
            {
                id: 4,
                title: "Chicken",
                amount: 10,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 5,
                title: "Eggs",
                amount: 9,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 6,
                title: "Kinder milk",
                amount: 200,
                category: Category.GROCERIES,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 7,
                title: "fess",
                amount: 170,
                category: Category.KIDS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 8,
                title: "House rent",
                amount: 1200,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 9,
                title: "Electricity",
                amount: 70,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 10,
                title: "Internet",
                amount: 20,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 11,
                title: "transport",
                amount: 49,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 12,
                title: "savings",
                amount: 500,
                category: Category.SAVINGS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 13,
                title: "Miscellaneous",
                amount: 200,
                category: Category.BILLS,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
        ]
    }    
]